export const clothesData = [
  {
    clothing_type: "t-shirt",
    size: "L",
    color: "Fuscia",
    material: "wool",
    brand: "Skinder",
    price: 74.12,
    in_stock: false,
    season: "winter",
    product_code: 1929,
    date_added: "6/4/2021",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWbR8M2NGY5mBAZCVsFL7oNk7Se1I38DsIZQ&usqp=CAU",
  },
  {
    clothing_type: "sweater",
    size: "L",
    color: "Mauv",
    material: "velvet",
    brand: "Devbug",
    price: 160.62,
    in_stock: true,
    season: "summer",
    product_code: 5164,
    date_added: "12/29/2021",
    image: "http://dummyimage.com/233x100.png/ff4444/ffffff",
  },
  {
    clothing_type: "shirt",
    size: "M",
    color: "Khaki",
    material: "silk",
    brand: "Myworks",
    price: 355.4,
    in_stock: true,
    season: "spring",
    product_code: 6490,
    date_added: "7/1/2020",
    image: "http://dummyimage.com/169x100.png/dddddd/000000",
  },
  {
    clothing_type: "jeans",
    size: "XS",
    color: "Teal",
    material: "polyester",
    brand: "Quinu",
    price: 115.36,
    in_stock: true,
    season: "spring",
    product_code: 5520,
    date_added: "2/17/2020",
    image: "http://dummyimage.com/207x100.png/cc0000/ffffff",
  },
  {
    clothing_type: "t-shirt",
    size: "S",
    color: "Violet",
    material: "linen",
    brand: "Jamia",
    price: 483.39,
    in_stock: true,
    season: "spring",
    product_code: 2647,
    date_added: "1/16/2020",
    image: "http://dummyimage.com/125x100.png/cc0000/ffffff",
  },
  {
    clothing_type: "blouse",
    size: "M",
    color: "Turquoise",
    material: "cotton",
    brand: "Innotype",
    price: 85.66,
    in_stock: false,
    season: "summer",
    product_code: 7477,
    date_added: "1/19/2021",
    image: "http://dummyimage.com/169x100.png/dddddd/000000",
  },
  {
    clothing_type: "jeans",
    size: "XS",
    color: "Turquoise",
    material: "silk",
    brand: "Flashpoint",
    price: 121.59,
    in_stock: true,
    season: "summer",
    product_code: 7705,
    date_added: "9/13/2021",
    image: "http://dummyimage.com/137x100.png/dddddd/000000",
  },
  {
    clothing_type: "sweater",
    size: "L",
    color: "Puce",
    material: "cotton",
    brand: "Jaloo",
    price: 239.22,
    in_stock: false,
    season: "spring",
    product_code: 1034,
    date_added: "5/28/2020",
    image: "http://dummyimage.com/147x100.png/5fa2dd/ffffff",
  },
  {
    clothing_type: "skirt",
    size: "XS",
    color: "Purple",
    material: "wool",
    brand: "Yodo",
    price: 63.96,
    in_stock: false,
    season: "summer",
    product_code: 4322,
    date_added: "5/19/2021",
    image: "http://dummyimage.com/240x100.png/cc0000/ffffff",
  },
  {
    clothing_type: "sweater",
    size: "L",
    color: "Teal",
    material: "wool",
    brand: "Jayo",
    price: 359.21,
    in_stock: true,
    season: "fall",
    product_code: 3715,
    date_added: "9/14/2020",
    image: "http://dummyimage.com/230x100.png/cc0000/ffffff",
  },
  {
    clothing_type: "jacket",
    size: "XL",
    color: "Violet",
    material: "denim",
    brand: "Shuffledrive",
    price: 182.91,
    in_stock: false,
    season: "fall",
    product_code: 5999,
    date_added: "6/19/2020",
    image: "http://dummyimage.com/104x100.png/cc0000/ffffff",
  },
  {
    clothing_type: "pants",
    size: "M",
    color: "Blue",
    material: "cotton",
    brand: "Vitz",
    price: 369.54,
    in_stock: false,
    season: "fall",
    product_code: 9305,
    date_added: "5/4/2021",
    image: "http://dummyimage.com/142x100.png/5fa2dd/ffffff",
  },
  {
    clothing_type: "blouse",
    size: "M",
    color: "Turquoise",
    material: "wool",
    brand: "Yakidoo",
    price: 76.52,
    in_stock: true,
    season: "winter",
    product_code: 2948,
    date_added: "4/19/2020",
    image: "http://dummyimage.com/219x100.png/5fa2dd/ffffff",
  },
  {
    clothing_type: "shorts",
    size: "XS",
    color: "Red",
    material: "nylon",
    brand: "Brainverse",
    price: 442.83,
    in_stock: false,
    season: "spring",
    product_code: 9761,
    date_added: "5/28/2020",
    image: "http://dummyimage.com/146x100.png/dddddd/000000",
  },
  {
    clothing_type: "pants",
    size: "XL",
    color: "Pink",
    material: "denim",
    brand: "Cogilith",
    price: 222.71,
    in_stock: false,
    season: "spring",
    product_code: 4104,
    date_added: "6/20/2020",
    image: "http://dummyimage.com/135x100.png/5fa2dd/ffffff",
  },
  {
    clothing_type: "skirt",
    size: "M",
    color: "Khaki",
    material: "silk",
    brand: "Tagpad",
    price: 301.97,
    in_stock: false,
    season: "summer",
    product_code: 2632,
    date_added: "10/26/2020",
    image: "http://dummyimage.com/162x100.png/cc0000/ffffff",
  },
  {
    clothing_type: "jeans",
    size: "M",
    color: "Fuscia",
    material: "polyester",
    brand: "Chatterbridge",
    price: 293.53,
    in_stock: false,
    season: "winter",
    product_code: 5891,
    date_added: "10/5/2021",
    image: "http://dummyimage.com/219x100.png/ff4444/ffffff",
  },
  {
    clothing_type: "jeans",
    size: "M",
    color: "Purple",
    material: "velvet",
    brand: "Tavu",
    price: 158.78,
    in_stock: true,
    season: "winter",
    product_code: 6924,
    date_added: "9/24/2021",
    image: "http://dummyimage.com/226x100.png/cc0000/ffffff",
  },
  {
    clothing_type: "blouse",
    size: "S",
    color: "Aquamarine",
    material: "linen",
    brand: "Eamia",
    price: 76.55,
    in_stock: false,
    season: "winter",
    product_code: 2179,
    date_added: "12/29/2021",
    image: "http://dummyimage.com/180x100.png/ff4444/ffffff",
  },
  {
    clothing_type: "jacket",
    size: "M",
    color: "Purple",
    material: "leather",
    brand: "Realpoint",
    price: 103.6,
    in_stock: false,
    season: "summer",
    product_code: 9202,
    date_added: "7/20/2021",
    image: "http://dummyimage.com/191x100.png/dddddd/000000",
  },
];
